"use client";

import { useForm } from "@tanstack/react-form";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useLoginMutation } from "@/lib/mutation/useLoginMutation";
import { LoginSchema } from "@/lib/schema/LoginSchema";
import { tvc } from "@/lib/tvc";
import { FormField } from "@/ui/form/FormField";

/**
 * Styles are generated by the AI, form logic is mine.
 * Shared field styles now live in FormField to avoid repetition.
 */

export default function LoginPage() {
	const loginMutation = useLoginMutation();
	const router = useRouter();

	const form = useForm({
		defaultValues: {
			email: "",
			password: "",
		} satisfies LoginSchema.Type,
		validators: {
			onSubmit: LoginSchema,
		},
		onSubmit: async ({ value }) => {
			const result = await loginMutation.mutateAsync(value);
			router.push("/user/profile");
			return result;
		},
	});

	const { Field, Subscribe } = form;

	return (
		<div
			className={tvc([
				"space-y-8",
			])}
		>
			<form
				className={tvc([
					"space-y-6",
				])}
				onSubmit={(event) => {
					event.preventDefault();
					void form.handleSubmit();
				}}
			>
				<Field name="email">
					{(field) => (
						<FormField
							label="Email"
							field={field}
							input={(props) => (
								<input
									{...props}
									id={field.name}
									type="email"
									value={field.state.value}
									onChange={(event) => {
										field.handleChange(event.target.value);
									}}
									onBlur={() => field.handleBlur()}
									placeholder="jane@example.com"
									autoComplete="email"
								/>
							)}
						/>
					)}
				</Field>

				<Field name="password">
					{(field) => (
						<FormField
							label="Password"
							field={field}
							input={(props) => (
								<input
									{...props}
									id={field.name}
									type="password"
									value={field.state.value}
									onChange={(event) => {
										field.handleChange(event.target.value);
									}}
									onBlur={() => field.handleBlur()}
									placeholder="Your password"
									autoComplete="current-password"
								/>
							)}
						/>
					)}
				</Field>

				<Subscribe
					selector={(state) => ({
						canSubmit: state.canSubmit,
						isSubmitting: state.isSubmitting,
					})}
				>
					{({ canSubmit, isSubmitting }) => (
						<button
							type="submit"
							className={tvc([
								"w-full",
								"rounded-xl",
								"bg-zinc-900",
								"px-4",
								"py-2",
								"text-sm",
								"font-medium",
								"text-white",
								"transition",
								"hover:bg-zinc-700",
								"disabled:cursor-not-allowed",
								"disabled:bg-zinc-400",
							])}
							disabled={!canSubmit || isSubmitting}
						>
							{isSubmitting ? "Signing in…" : "Sign in"}
						</button>
					)}
				</Subscribe>
			</form>

			<div
				className={tvc([
					"space-y-4",
					"text-center",
					"text-sm",
					"text-zinc-600",
				])}
			>
				<div>
					New to Elasticle?{" "}
					<Link
						className={tvc([
							"font-medium",
							"text-zinc-900",
							"underline",
						])}
						href="/public/register"
					>
						Create an account
					</Link>
				</div>

				{/*
                    This is just naive error - we're expecting BE works properly, so the only
                    error can be wrong credentials 
                 */}
				{loginMutation.isError ? (
					<div
						className={tvc([
							"rounded-xl",
							"border",
							"border-red-200",
							"bg-red-50",
							"px-4",
							"py-2",
							"text-sm",
							"text-red-700",
						])}
					>
						Wrong user name or password.
					</div>
				) : null}
			</div>
		</div>
	);
}
