import Link from "next/link";
import { tvc } from "@/lib/tvc";

export default function Home() {
	return (
		<main
			className={tvc([
				"flex",
				"min-h-screen",
				"items-center",
				"justify-center",
				"bg-zinc-50",
				"py-24",
				"px-6",
			])}
		>
			<div
				className={tvc([
					"w-full",
					"max-w-3xl",
					"rounded-3xl",
					"border",
					"border-zinc-200",
					"bg-white",
					"p-12",
					"shadow-sm",
					"space-y-8",
					"text-center",
				])}
			>
				<div
					className={tvc([
						"space-y-4",
					])}
				>
					<h1
						className={tvc([
							"text-3xl",
							"font-semibold",
							"text-zinc-900",
						])}
					>
						Welcome to Elasticle
					</h1>
					<p
						className={tvc([
							"text-sm",
							"text-zinc-600",
						])}
					>
						Just some lorem ipsum for this landing page. Tadaa
					</p>
				</div>

				<div
					className={tvc([
						"flex",
						"flex-col",
						"items-center",
						"gap-3",
						"sm:flex-row",
						"sm:justify-center",
					])}
				>
					<Link
						className={tvc([
							"inline-flex",
							"items-center",
							"justify-center",
							"rounded-xl",
							"bg-zinc-900",
							"px-6",
							"py-2.5",
							"text-sm",
							"font-medium",
							"text-white",
							"transition",
							"hover:bg-zinc-800",
						])}
						href="/public/login"
					>
						Login
					</Link>
					<Link
						className={tvc([
							"inline-flex",
							"items-center",
							"justify-center",
							"rounded-xl",
							"border",
							"border-zinc-200",
							"px-6",
							"py-2.5",
							"text-sm",
							"font-medium",
							"text-zinc-700",
							"transition",
							"hover:border-zinc-300",
							"hover:text-zinc-900",
						])}
						href="/public/register"
					>
						Register
					</Link>
				</div>
			</div>
		</main>
	);
}
